# Generated by Django 2.2.7 on 2019-11-12 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0002_auto_20191112_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField()),
                ('project_type', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=200, null=True)),
                ('budget', models.CharField(max_length=255, null=True)),
                ('dev_platfrom', models.CharField(max_length=255, null=True)),
                ('server_platform', models.CharField(max_length=255, null=True)),
                ('project_status', models.CharField(max_length=255, null=True)),
                ('payment_status', models.CharField(max_length=255, null=True)),
                ('payment_method', models.CharField(max_length=255, null=True)),
                ('client_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_id', to='project.Project')),
                ('project_manager_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_manager', to=settings.AUTH_USER_MODEL)),
                ('supervised_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='supervised_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_details',
            },
        ),
    ]
