# Generated by Django 2.2.7 on 2019-11-12 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project_detail',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='project_detail',
            old_name='project_manager_id',
            new_name='project_manager',
        ),
    ]
